"use client";

import { useState } from "react";
import { Bot, CheckCircle2, KeyRound, Plus, Settings2, ShieldAlert, X } from "lucide-react";
import type { WorkspaceSnapshot } from "@/lib/domain/types";
import type { WorkspaceCommandDraft } from "@/lib/domain/schemas";

type SendCommand = (draft: WorkspaceCommandDraft) => Promise<boolean>;

export function SettingsDialog({ snapshot, busy, sendCommand, onClose }: { snapshot: WorkspaceSnapshot; busy: boolean; sendCommand: SendCommand; onClose: () => void }) {
  const [tab, setTab] = useState<"model" | "agents" | "tools">("model");
  const [model, setModel] = useState(snapshot.settings.model); const [format, setFormat] = useState(snapshot.settings.apiFormat);
  const [thinkingMode, setThinkingMode] = useState(snapshot.settings.thinkingMode); const [reasoningEffort, setReasoningEffort] = useState(snapshot.settings.reasoningEffort);
  const [steps, setSteps] = useState(snapshot.settings.maxToolSteps); const [rounds, setRounds] = useState(snapshot.settings.maxRoomRounds);
  const [roots, setRoots] = useState(snapshot.settings.projectContextRoots.join("\n"));
  const [newAgent, setNewAgent] = useState({ label: "", summary: "", instruction: "" });
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="settings-dialog" role="dialog" aria-modal="true" aria-label="工作台设置">
    <header><div><span><Settings2 size={18} /></span><div><h2>工作台设置</h2><p>本地权威配置与 Agent 注册表</p></div></div><button className="icon-button" onClick={onClose}><X size={18} /></button></header>
    <div className="settings-body"><nav><button className={tab === "model" ? "active" : ""} onClick={() => setTab("model")}><KeyRound size={16} />模型连接</button><button className={tab === "agents" ? "active" : ""} onClick={() => setTab("agents")}><Bot size={16} />Agent 注册表</button><button className={tab === "tools" ? "active" : ""} onClick={() => setTab("tools")}><ShieldAlert size={16} />工具与安全</button></nav><div className="settings-content">
      {tab === "model" ? <><div className="setting-status"><CheckCircle2 size={17} /><span><strong>{snapshot.settings.apiKeyConfigured ? "全局真实模型已配置" : "正在使用确定性假模型"}</strong><small>所有 Agent、房间调度与 Cron 工作流在运行时读取同一份全局配置；API Key 不写入 SQLite</small></span></div><label>Base URL<input value={snapshot.settings.baseUrl} disabled /></label><label>全局默认模型<select value={model} onChange={(event) => setModel(event.target.value)}>{snapshot.settings.availableModels.map((availableModel) => <option value={availableModel} key={availableModel}>{availableModel}</option>)}</select></label><label>接口格式<select value={format} onChange={(event) => setFormat(event.target.value as typeof format)}><option value="auto">自动：Responses → Chat Completions</option><option value="responses">Responses</option><option value="chat_completions">Chat Completions</option></select></label><div className="field-pair"><label>思考模式<select value={thinkingMode} onChange={(event) => setThinkingMode(event.target.value as typeof thinkingMode)}><option value="provider_default">跟随服务商默认</option><option value="enabled">启用</option><option value="disabled">禁用</option></select></label><label>思考强度<select value={reasoningEffort} disabled={thinkingMode === "disabled"} onChange={(event) => setReasoningEffort(event.target.value as typeof reasoningEffort)}><option value="high">High</option><option value="max">Max</option></select></label></div><div className="field-pair"><label>最大工具步骤<input type="number" min={1} max={64} value={steps} onChange={(event) => setSteps(Number(event.target.value))} /></label><label>房间最大轮次<input type="number" min={1} max={256} value={rounds} onChange={(event) => setRounds(Number(event.target.value))} /></label></div><label>项目上下文根目录<textarea rows={5} value={roots} onChange={(event) => setRoots(event.target.value)} placeholder="每行一个绝对路径" /></label><button className="primary-button" disabled={busy} onClick={() => void sendCommand({ type: "update_settings", model, availableModels: snapshot.settings.availableModels, apiFormat: format, thinkingMode, reasoningEffort, maxToolSteps: steps, maxRoomRounds: rounds, projectContextRoots: roots.split(/\r?\n/).map((item) => item.trim()).filter(Boolean) })}>保存全局模型设置</button></> : null}
      {tab === "agents" ? <><div className="agent-setting-list">{snapshot.agents.map((agent) => <article key={agent.id}><span><Bot size={17} /></span><div><strong>{agent.label}</strong><p>{agent.summary}</p><code>{agent.id}</code></div></article>)}</div><div className="new-agent-form"><h3><Plus size={15} />创建 Agent</h3><label>名称<input value={newAgent.label} onChange={(event) => setNewAgent({ ...newAgent, label: event.target.value })} /></label><label>简介<input value={newAgent.summary} onChange={(event) => setNewAgent({ ...newAgent, summary: event.target.value })} /></label><label>指令<textarea rows={5} value={newAgent.instruction} onChange={(event) => setNewAgent({ ...newAgent, instruction: event.target.value })} /></label><button className="primary-button" disabled={busy || !newAgent.label || !newAgent.instruction} onClick={async () => { if (await sendCommand({ type: "create_agent", ...newAgent })) setNewAgent({ label: "", summary: "", instruction: "" }); }}>加入注册表</button></div></> : null}
      {tab === "tools" ? <><div className="danger-notice"><ShieldAlert size={20} /><div><strong>全盘 shell · 无审批</strong><p>Agent shell 继承启动 OceanKing 的 Windows 用户权限，包括高危命令在内均自动执行。Panic Stop 会终止活动进程树，但不能撤销已经完成的副作用。</p></div></div><div className="tool-policy-list"><div><strong>工作区工具</strong><span>私有/共享根目录防路径穿越</span></div><div><strong>网页抓取</strong><span>拒绝 localhost 与内网地址</span></div><div><strong>房间工具</strong><span>成员关系与 owner 权限双重校验</span></div><div><strong>API 服务</strong><span>仅监听 127.0.0.1 并校验 Origin</span></div></div></> : null}
    </div></div>
  </section></div>;
}
